sudo: required
  
services:
  - docker

language: java

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./gradlew clean assemble

after_success:
  - docker build -t sdkman/candidates:"$TRAVIS_BUILD_NUMBER" .
  - docker push sdkman/sdkman-candidates:"$TRAVIS_BUILD_NUMBER"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
